---
- name: install cloudwatch-agent
  become: yes
  dnf:
    name:
      - https://amazoncloudwatch-agent.s3.amazonaws.com/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
      - awscli
    state: present
