---
- name: create admin user
  become: yes
  user:
    name: "{{item.name}}"
    state: present
    comment: admin user
    groups: wheel
    append: yes
    create_home: yes
    password: "{{item.password | password_hash('sha512', inventory_hostname | random(seed=inventory_hostname) | string)}}"
  loop: "{{ admin_users | community.general.lists_mergeby(admin_passwords, 'name') }}"

- name: add ssh keys
  become: yes
  ansible.posix.authorized_key:
    user: "{{item.0.name}}"
    state: present
    key: "{{item.1}}"
  with_subelements:
    - "{{admin_users}}"
    - keys

- name: deploy sudo configuration
  become: yes
  template:
    src: admin-sudoers
    dest: /etc/sudoers.d/admin-sudoers
    owner: root
    mode: '0600'
