---
- name: restrict file permissions for cronjobs directories
  file:
    mode: '0700'
    path: "{{item}}" 
  loop:
    - /etc/crontab
    - /etc/cron.d
    - /etc/cron.deny
    - /etc/cron.hourly
    - /etc/cron.weekly
    - /etc/cron.daily
    - /etc/cron.monthly
  
