# This is a basic workflow to help you get started with Actions
name: deploy baseline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: fedora:39

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install Ansible
        run: |
          dnf install -y ansible openssh-clients

      - name: prepare credentials
        run: |
          mkdir ~/.ssh
          umask 077
          cat > ~/.ssh/known_hosts <<EOF
          [chicago.akdev.xyz]:5322 ${{ vars.CHICAGO_HOST_KEY }}
          EOF
          cat > ~/.ssh/id_ecdsa <<EOF
          ${{ secrets.MANAGEMENT_SSH_PRIVATE_KEY }}
          EOF
          cat > .vault-password <<EOF
          ${{ secrets.MANAGEMENT_PASSWORD }}
          EOF
          
      - name: deploy basic configuration
        run: |
          ansible-playbook basic-config.yml
          
      # Runs a set of commands using the runners shell
      - name: deploy security policies
        run: |
          ansible-playbook security.yml
